### ISSUE TITLE
TypeError: apply_async() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by kupuguy** [obsidiancard/django-allauth-djrill#3]
When celery is not installed, the fallback code in tasks.py includes a spurious `self` parameter. This makes the call to `apply_async` fail:

    File ".../python3.4/site-packages/allauth_djrill/adapter.py", line 43, in send_mail
      send_mandrill_template_mail.apply_async(kwargs={
    TypeError: apply_async() missing 1 required positional argument: 'self'

The fix is simply to delete the parameter `self,` from line 11 of tasks.py.

**Comment by tarkatronic** [comment]
Ah right. I'm not really sure how that snuck in there. Thanks for the report! Good to see this is getting some use.

**Comment by tarkatronic** [comment]
v0.1.1 is now available on PyPi with this fix
