### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by philippeluickx** [obsidiancard/django-allauth-djrill#7]
The adapter is not being called when doing a reset password. Email is sent the traditional way.

**Comment by tarkatronic** [comment]
Is the adapter being called for you in other cases? If you are using the allauth password reset view (and not the built-in Django password reset view) then the adapter should be getting called: https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L442

**Comment by philippeluickx** [comment]
Good point, let me check this. I am using this together with https://github.com/Tivix/django-rest-auth so there might be some differences in implementation...

**Comment by philippeluickx** [comment]
You are right, the django implementation is  used for password reset:
from django.contrib.auth.forms import PasswordResetForm

https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py
